# fly.toml app configuration file generated for quiet-night-7393 on 2023-08-10T22:29:38-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-night-7393"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
