GET http://localhost:3003/api/blog
###
GET http://localhost:3003/api/blog/64543fb0687f82a5c41af97e
###
GET http://localhost:3003/api/blog/wrongid
###
POST http://localhost:3003/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "root",
  "password": "sosecret"
}
###
POST http://localhost:3003/api/blog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NTQ4N2NhMDdlMTQ2YTI0YWE5OTNkOCIsImlhdCI6MTY4MzI3MDA4MSwiZXhwIjoxNjgzMjczNjgxfQ.JCDTnMgxPUBkUHQ6tuGQc5EfivGb6FA5K68gUQTaSwU

{
  "title": "testing asd",
  "author": "test suleymanoglu",
  "url": "testtestest.com"
}
###
POST http://localhost:3003/api/blog HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY0NTQ4N2NhMDdlMTQ2YTI0YWE5OTNkOCIsImlhdCI6MTY4MzI3MDA4MSwiZXhwIjoxNjgzMjczNjgxfQ.JCDTnMgxPUBkUHQ6tuGQc5EfivGb6FA5K68gUQTaSwU

{
  "title": "testing second time",
  "author": "test suleymanoglu",
  "url": "testtestest.com"
}
###
POST http://localhost:3003/api/blog HTTP/1.1
Content-Type: application/json

{
      "title": "Test blog",
      "author": "Test author",
      "url": "https://testblog.com/",
      "likes": 0
}
